### GET request to example server
GET http://localhost:8080/users

###

GET http://localhost:8080/users

### Criar um novo usuário
POST http://localhost:8080/users
Content-Type: application/json

{
  "name": "Jose Bonifacio",
  "email": "jose@gmail.com"
}

###
DELETE http://localhost:8080/users/698b7fa1691ab241e9c106c4

### Atualizar um usuário existente
PUT http://localhost:8080/users/698b949bf4f84bf541072bf1
Content-Type: application/json

{
  "name": "Maria Silva Sauro",
  "email": "maria.nova@gmail.com"
}

###

GET http://localhost:8080/users/698f21c8e68c0179a747b0b5/posts


###

GET http://localhost:8080/posts/698f28023f01d5092909e548

###

GET http://localhost:8080/posts/titlesearch?text=aa