### GET request to example server
GET http://localhost:8080/users

###

GET http://localhost:8080/users/698a2067c521483e3ea99201

### Criar um novo usuário
POST http://localhost:8080/users
Content-Type: application/json

{
  "name": "Jose Bonifacio",
  "email": "jose@gmail.com"
}

###
DELETE http://localhost:8080/users/698b7fa1691ab241e9c106c4